### ISSUE TITLE
Warning: SwissEph file 'sepl_18.se1' not found in the paths of: '/data/ephemeris'

### ISSUE THREAD

**Issue by kbridgford** [Kibo/AstroWebService#1]
When running bootstrap.java, the following warning occurs:

`Warning: SwissEph file 'sepl_18.se1' not found in the paths of: '/data/ephemeris',
using Moshier eph.;`

I put the .se1 files in /public/data/ephemeris, and verified that they were there via browser (see attached image).

![Capture](https://user-images.githubusercontent.com/57777806/68906064-6f7bcc00-0700-11ea-9d18-bdd6d5105ae1.PNG)

**Comment by Kibo** [comment]
Hi,
https://github.com/Kibo/AstroAPI#install
Tom
